version: 2

jobs:
  build:
    docker:
      - image: liuchong/rustup:nightly
    working_directory: ~/src/
    steps:
      - checkout
      - run:
          name: Compile
          command: cargo build --verbose
      - run:
          name: Test
          command: cargo test --verbose
      - run:
          name: Build documentation
          command: cargo doc
      - persist_to_workspace:
          root: .
          paths:
            - target/doc/

  lint:
    docker:
      - image: liuchong/rustup:nightly
    environment:
      RUST_VERSION: nightly-2018-01-12
      CLIPPY_VERSION: 0.0.179
    working_directory: ~/src/
    steps:
      - checkout
      - run:
          name: Install rust, clippy, and rustfmt
          command: |
            rustup toolchain install "${RUST_VERSION}"
            rustup default "${RUST_VERSION}"
            rustup component add rustfmt-preview
            cargo install clippy --version "${CLIPPY_VERSION}"

      - run:
          name: rustfmt
          command: cargo fmt -- --write-mode=diff

      - run:
          name: clippy
          when: always
          command: cargo clippy -- -D clippy

  deploy:
    docker:
      - image: debian:jessie-slim
    working_directory: ~/src/
    steps:
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y ca-certificates git ssh
      - checkout
      - attach-workspace:
          at: .
      - run:
          name: Generate documentation index
          command: |
            cat >target/doc/index.html <<EOF
            <!doctype html>
            <html>
            <head>
            <meta http-equiv="refresh" content="0; url=https://irkd.github.io/irksome/irksome/index.html">
            </head>
            </html>
            EOF
      - add_ssh_keys:
          fingerprints:
            - "c1:92:32:06:af:77:ec:4a:16:4f:46:83:d2:59:d5:49"
      - run:
          name: Configure Git
          command: |
            git config --global user.email deploy@brennie.ca
            git config --global user.name "Circle CI"
      - deploy:
          name: Push to gh-pages
          command: |
            mkdir -p target/doc/.circleci
            cp .circleci/config.yml target/doc/.circleci/config.yml
            git add -f target/doc
            git commit -m  "Build documentation for ${CIRCLE_SHA1}"
            git subtree split --prefix=target/doc -b gh-pages
            git push -f origin gh-pages:gh-pages

workflows:
  version: 2
  build-lint-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages

      - lint:
          filters:
            branches:
              ignore:
                - gh-pages

      - deploy:
          requires:
            - build
            - lint
          filters:
            branches:
              only:
                - master
